CREATE SCHEMA ISCRIZIONI;
use ISCRIZIONI;


CREATE TABLE DOCENTI
          (
           CF VARCHAR(25) PRIMARY KEY,
           PASSWORD VARCHAR(25),
           NOME VARCHAR(25),
           COGNOME VARCHAR(25)
          );
          
  CREATE TABLE SEGRETARIE
         (
           CF VARCHAR(25) PRIMARY KEY,
           PASSWORD VARCHAR(25),
            NOME VARCHAR(25),
           COGNOME VARCHAR(25)
          );
          
CREATE TABLE STUDENTI
          (
           CF VARCHAR(25) PRIMARY KEY,
           PASSWORD VARCHAR(25),
           NOME VARCHAR(25),
           COGNOME VARCHAR(25),
           EMAIL VARCHAR(25),
           NUMERO INTEGER,
           MATRICOLA INTEGER
          );
CREATE TABLE CORSI
          (
          CODICE INTEGER PRIMARY KEY,
          CFU NUMERIC,
          NOME VARCHAR(25)
          );          
          
          
 CREATE TABLE RICHIESTAPRENOTAZIONI(
        CODICE INTEGER PRIMARY KEY,
        SESSIONEESAME DATE
 );     
 
  CREATE TABLE RICHIESTESPOSTAMENTI(
        CODICE INTEGER PRIMARY KEY
 );
 
 CREATE TABLE PIANODISTUDIPARTI(
 
 CFSTUDENTE VARCHAR(25)  references STUDENTI(CF), 
 ANNO INTEGER,
 PRIMARY KEY(CFSTUDENTE,ANNO)
 
 )ENGINE = InnoDB;
 
 CREATE TABLE PIANODISTUDIO(
 
 CFSTUDENTE VARCHAR(25),
 ANNO INTEGER,
 CODICECORSO INTEGER  references CORSI(CODICE),
 
 PRIMARY KEY(CFSTUDENTE, ANNO, CODICECORSO),
 FOREIGN KEY (CFSTUDENTE, ANNO) REFERENCES PIANIDISTUDIPARTI(CFSTUDENTE, ANNO) 
 
 )ENGINE = InnoDB;
 
 CREATE TABLE LIBRETTISTUDENTE (
 CFSTUDENTE VARCHAR(25) references STUDENTI(CF),
 CODICECORSO  INTEGER references CORSI(CODICE),
 VOTO INTEGER,
 
 PRIMARY KEY(CFSTUDENTE, CODICECORSO)
 
 );
 
 CREATE TABLE TASSE(
 
 CODICE INTEGER,
 CFSTUDENTE VARCHAR(25) references STUDENTI(CF),
 
 PRIMARY KEY(CODICE, CFSTUDENTE)
 
 )ENGINE = InnoDB;
 
  CREATE TABLE APPELLI(
 
ORA TIME,
DATAAPPELLO DATE,
AULA VARCHAR(25),
MODALITA VARCHAR(25),
CFDOCENTE VARCHAR(25)references DOCENTI(CF),
CODICECORSO INTEGER references CORSI(CODICE),

PRIMARY KEY(ORA, DATAAPPELLO, AULA)
 
 
 )ENGINE = InnoDB;
 
 CREATE TABLE ISCRIZIONI(
 
CODICE INTEGER PRIMARY KEY,
CFSTUDENTE VARCHAR(25)references STUDENTI(CF),
ORAAPPELLO TIME,
DATAAPPELLO DATE,
AULAAPPELLO VARCHAR(25),
 
FOREIGN KEY (ORAAPPELLO,DATAAPPELLO,AULAAPPELLO) REFERENCES APPELLI(ORA,DATAAPPELLO,AULA)
  
 
 )ENGINE = InnoDB;
 

 
 
 
 
 
 
 
 
 INSERT INTO CORSI (CODICE, CFU, NOME) VALUES (1, 6, "NNOME"); 
 INSERT INTO DOCENTI (CF, PASSWORD, NOME, COGNOME) VALUES ("JSKHDJKASHD", "PASSWORD", "NOME", "COGNOME"); 
 